### ISSUE TITLE
Add Unity 5.6 beta support

### ISSUE THREAD

**Issue by DuFF14** [OSVR/OSVR-Unity#201]
search for #if UNITY_VERSION and add UNITY_5_6 where necessary. 
https://github.com/OSVR/OSVR-Unity/search?utf8=%E2%9C%93&q=%22%23if+UNITY%22&type=Code

**Comment by DuFF14** [comment]
addressed in https://github.com/OSVR/OSVR-Unity/pull/203

**Comment by amiga** [comment]
Has this been fixed? I still get failed to create render manager in Unity 5.5.1.

**Comment by DuFF14** [comment]
@amiga sounds unrelated to this issue about Unity 5.6 support. Addressed your issue at https://github.com/OSVR/OSVR-Unity-Rendering/issues/25
